### ISSUE TITLE
More Slides

### ISSUE THREAD

**Issue by derSteffen** [jillix/jQuery-sidebar#9]
Hello,

how can i add more slides? I use the handler.js from the demo, but i can't add more slides?

I add div2bottom to var slides and div2bottom: [-height, 0] to range and add div2bottom to my css and in this is my html

.. and in the .sidebars-DIV this:

	<div class="sidebar div2bottom">	
		<h1>YYYYY</h1>
	</div>

Please! I need help!

Thanks!

Or is there an documentation with normal examples?

**Comment by IonicaBizau** [comment]
Do you need more bottom sidebars? If so, just create two HTML elements:
```html
<div class="sidebar bottom">    
    <h1>Sidebar 1</h1>
</div>

<div class="sidebar bottom">    
    <h1>Sidebar 2</h1>
</div>
```

And then you can do:

```js
$(".sidebar.bottom").sidebar({ side: "bottom" });
```

For triggering events you will use:

```js
// Open the first sidebar
$(".sidebar.bottom:eq(0)").trigger("sidebar:open");

// Open the second sidebar
$(".sidebar.bottom:eq(1)").trigger("sidebar:open");
```

**Comment by derSteffen** [comment]
Hello, thanks for your answer!

My problem is, that I dont have an example-code for sidebar .. only the handler.js .. and I cant code special click-events to trigger open/close this sidebar if i click on this link!

If I delete the handler nothing is going!

Greetings

**Comment by derSteffen** [comment]
Thats my Code

but nothing is going.

The divs always showing ... and the js makes nothing

HTML
```html
	<a href="#" class="btn button" data-action="toggle" data-side="left">Kontakt</a>
		<a href="#" class="btn button" data-action="toggle" data-side="top">Lage</a>
		<a href="#" class="btn button" data-action="toggle" data-side="right">Impressum</a>
		<a href="#" class="btn button" data-action="toggle" data-side="bottom">Wir über uns</a>
		<a href="#" class="btn button" data-action="toggle" data-side="bottom">XXX</a>
	

<div class="sidebar left" >
	<a href="#" class="closeicon btn" title="Schließen" data-action="close" data-side="left"><img src="images/close.png" alt="Schließen"  width="46" height="47" /></a>
		<h1>Wir über uns</h1>
		<p><br />Inhalt folgt demnächst!</p>
	</div>

<div class="sidebar top" >
	<a href="#" class="closeicon btn" title="Schließen" data-action="close" data-side="top"><img src="images/close.png" alt="Schließen"  width="46" height="47" /></a>
		<h1>Wir über uns</h1>
		<p><br />Inhalt folgt demnächst!</p>
	</div>

	<div class="sidebar bottom" >
	<a href="#" class="closeicon btn" title="Schließen" data-action="close" data-side="bottom"><img src="images/close.png" alt="Schließen"  width="46" height="47" /></a>
		<h1>Wir über uns</h1>
		<p><br />Inhalt folgt demnächst!</p>
	</div>

	<div class="sidebar bottom">
	<a href="#" class="closeicon btn" title="Schließen" data-action="close" data-side="bottom"><img src="images/close.png" alt="Schließen"  width="46" height="47" /></a>
		<h1>YYYYY</h1>
		<p><br /></p>
	</div>
```
JS
```javascript
$(document).ready(function () {
$(".sidebar.bottom").sidebar({ side: "bottom" });

// Open the first sidebar
$(".sidebar.bottom:eq(0)").trigger("sidebar:open");

// Open the second sidebar
$(".sidebar.bottom:eq(1)").trigger("sidebar:open");
});
```
CSS
```css
.sidebar.left {
    top: 0;
    left: 0;
    bottom: 0;
    width: 640px;
	height: 100%;

}

.sidebar.right {
    top: 0;
    right: 0;
    bottom: 0;
    width: 640px;
	height: 100%;
}

.sidebar.bottom {
    left: 0;
    right: 0;
    bottom: 0;
    height:100%;
	max-height:260px;
}


.sidebar.top {
    left: 0;
    right: 0;
    top: 0;
    height:100%;
	max-height:500px;
}
```
